services:
  odoo:
    image: ev-odoo:latest
    command: ["-c", "./run-profiles/local-ubuntu/env.conf", "-i", "factory", "--without-demo", "all"]
    restart: always
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - "../../data/ebrahem_factory/odoo:/var/lib/odoo"
      - "../../license:/ev-odoo/license"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - "../../data/ebrahem_factory/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
